# Generated by Django 2.1.5 on 2020-05-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
