# Generated by Django 2.1.5 on 2020-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Work', 'Work'), ('Animals', 'Animals'), ('Electronics', 'Electronics'), ('Sport', 'Sport')], max_length=100),
        ),
    ]
