# Generated by Django 2.1.5 on 2020-05-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='times_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
