# Generated by Django 2.1.5 on 2020-05-19 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_of_create',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
