# Generated by Django 2.1.5 on 2020-05-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0005_auto_20200519_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
