# Generated by Django 2.1.5 on 2020-05-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0006_message_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
